-- CreateEnum
CREATE TYPE "QuoteStatus" AS ENUM (
  'REQUESTED',
  'PRICING',
  'SENT',
  'CLIENT_PROPOSED_CHANGES',
  'CLIENT_APPROVED',
  'CLIENT_REJECTED',
  'CONVERTED',
  'EXPIRED'
);

-- AlterTable
ALTER TABLE "Quote" ADD COLUMN "expiresAt" TIMESTAMP(3);
ALTER TABLE "Quote" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Quote"
ALTER COLUMN "status" TYPE "QuoteStatus"
USING (
  CASE "status"
    WHEN 'REQUESTED' THEN 'REQUESTED'
    WHEN 'PRICING' THEN 'PRICING'
    WHEN 'SENT' THEN 'SENT'
    WHEN 'CLIENT_PROPOSED_CHANGES' THEN 'CLIENT_PROPOSED_CHANGES'
    WHEN 'CLIENT_APPROVED' THEN 'CLIENT_APPROVED'
    WHEN 'CLIENT_REJECTED' THEN 'CLIENT_REJECTED'
    WHEN 'CONVERTED' THEN 'CONVERTED'
    WHEN 'EXPIRED' THEN 'EXPIRED'
    ELSE 'REQUESTED'
  END
)::"QuoteStatus";
ALTER TABLE "Quote" ALTER COLUMN "status" SET DEFAULT 'REQUESTED';
