-- CreateEnum
CREATE TYPE "OrderStatus" AS ENUM (
  'PENDING',
  'CONFIRMED',
  'READY',
  'IN_TRANSIT',
  'DELIVERED',
  'CANCELLED',
  'QUOTE_PENDING',
  'IN_PREPARATION',
  'READY_FOR_PICKUP',
  'UNDER_REVIEW',
  'COMPLETED',
  'DISPUTED'
);

-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Order"
ALTER COLUMN "status" TYPE "OrderStatus"
USING (
  CASE "status"
    WHEN 'PENDING' THEN 'PENDING'
    WHEN 'CONFIRMED' THEN 'CONFIRMED'
    WHEN 'READY' THEN 'READY'
    WHEN 'IN_TRANSIT' THEN 'IN_TRANSIT'
    WHEN 'DELIVERED' THEN 'DELIVERED'
    WHEN 'CANCELLED' THEN 'CANCELLED'
    WHEN 'QUOTE_PENDING' THEN 'QUOTE_PENDING'
    WHEN 'IN_PREPARATION' THEN 'IN_PREPARATION'
    WHEN 'READY_FOR_PICKUP' THEN 'READY_FOR_PICKUP'
    WHEN 'UNDER_REVIEW' THEN 'UNDER_REVIEW'
    WHEN 'COMPLETED' THEN 'COMPLETED'
    WHEN 'DISPUTED' THEN 'DISPUTED'
    ELSE 'PENDING'
  END
)::"OrderStatus";
ALTER TABLE "Order" ALTER COLUMN "status" SET DEFAULT 'PENDING';
